export const DAILY_VERSES = [
  {
    ref: "Philippians 4:13",
    text: "I can do all things through Christ which strengtheneth me.",
    verse: 13,
    book: "Philippians",
    chapter: 4,
  },
  {
    ref: "Jeremiah 29:11",
    text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
    verse: 11,
    book: "Jeremiah",
    chapter: 29,
  },
  {
    ref: "Isaiah 40:31",
    text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    verse: 31,
    book: "Isaiah",
    chapter: 40,
  },
  {
    ref: "Joshua 1:9",
    text: "Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    verse: 9,
    book: "Joshua",
    chapter: 1,
  },
  {
    ref: "Psalm 119:105",
    text: "Thy word is a lamp unto my feet, and a light unto my path.",
    verse: 105,
    book: "Psalms",
    chapter: 119,
  },
  {
    ref: "2 Corinthians 5:17",
    text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    verse: 17,
    book: "2 Corinthians",
    chapter: 5,
  },
  {
    ref: "Romans 8:28",
    text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    verse: 28,
    book: "Romans",
    chapter: 8,
  },
  {
    ref: "Proverbs 3:5",
    text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
    verse: 5,
    book: "Proverbs",
    chapter: 3,
  },
  {
    ref: "Psalm 37:4",
    text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
    verse: 4,
    book: "Psalms",
    chapter: 37,
  },
  {
    ref: "Matthew 6:33",
    text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    verse: 33,
    book: "Matthew",
    chapter: 6,
  },
  {
    ref: "Psalm 23:4",
    text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    verse: 4,
    book: "Psalms",
    chapter: 23,
  },
  {
    ref: "Isaiah 43:2",
    text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.",
    verse: 2,
    book: "Isaiah",
    chapter: 43,
  },
  {
    ref: "Psalm 27:1",
    text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    verse: 1,
    book: "Psalms",
    chapter: 27,
  },
  {
    ref: "Romans 15:13",
    text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    verse: 13,
    book: "Romans",
    chapter: 15,
  },
  {
    ref: "Psalm 46:10",
    text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.",
    verse: 10,
    book: "Psalms",
    chapter: 46,
  },
  {
    ref: "1 Corinthians 16:14",
    text: "Let all your things be done with charity.",
    verse: 14,
    book: "1 Corinthians",
    chapter: 16,
  },
  {
    ref: "Psalm 34:8",
    text: "O taste and see that the LORD is good: blessed is the man that trusteth in him.",
    verse: 8,
    book: "Psalms",
    chapter: 34,
  },
  {
    ref: "Psalm 121:1",
    text: "I will lift up mine eyes unto the hills, from whence cometh my help.",
    verse: 1,
    book: "Psalms",
    chapter: 121,
  },
  {
    ref: "Psalm 51:10",
    text: "Create in me a clean heart, O God; and renew a right spirit within me.",
    verse: 10,
    book: "Psalms",
    chapter: 51,
  },
  {
    ref: "Psalm 19:14",
    text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.",
    verse: 14,
    book: "Psalms",
    chapter: 19,
  },
  {
    ref: "Psalm 16:8",
    text: "I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
    verse: 8,
    book: "Psalms",
    chapter: 16,
  },
  {
    ref: "Psalm 62:8",
    text: "Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us.",
    verse: 8,
    book: "Psalms",
    chapter: 62,
  },
  {
    ref: "Psalm 18:2",
    text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust.",
    verse: 2,
    book: "Psalms",
    chapter: 18,
  },
  {
    ref: "Psalm 20:7",
    text: "Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.",
    verse: 7,
    book: "Psalms",
    chapter: 20,
  },
  {
    ref: "Psalm 25:4",
    text: "Shew me thy ways, O LORD; teach me thy paths.",
    verse: 4,
    book: "Psalms",
    chapter: 25,
  },
  {
    ref: "Psalm 31:24",
    text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
    verse: 24,
    book: "Psalms",
    chapter: 31,
  },
  {
    ref: "Psalm 33:20",
    text: "Our soul waiteth for the LORD: he is our help and our shield.",
    verse: 20,
    book: "Psalms",
    chapter: 33,
  },
  {
    ref: "Psalm 40:1",
    text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry.",
    verse: 1,
    book: "Psalms",
    chapter: 40,
  },
  {
    ref: "Psalm 55:22",
    text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.",
    verse: 22,
    book: "Psalms",
    chapter: 55,
  },
  {
    ref: "Psalm 56:3",
    text: "What time I am afraid, I will trust in thee.",
    verse: 3,
    book: "Psalms",
    chapter: 56,
  },
  {
    ref: "Psalm 91:1",
    text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.",
    verse: 1,
    book: "Psalms",
    chapter: 91,
  },
  {
    ref: "Psalm 103:1",
    text: "Bless the LORD, O my soul: and all that is within me, bless his holy name.",
    verse: 1,
    book: "Psalms",
    chapter: 103,
  },
  {
    ref: "Psalm 118:24",
    text: "This is the day which the LORD hath made; we will rejoice and be glad in it.",
    verse: 24,
    book: "Psalms",
    chapter: 118,
  },
  {
    ref: "Psalm 136:1",
    text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever.",
    verse: 1,
    book: "Psalms",
    chapter: 136,
  },
  {
    ref: "Psalm 139:14",
    text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.",
    verse: 14,
    book: "Psalms",
    chapter: 139,
  },
  {
    ref: "Psalm 143:8",
    text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk.",
    verse: 8,
    book: "Psalms",
    chapter: 143,
  },
  {
    ref: "Psalm 145:18",
    text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.",
    verse: 18,
    book: "Psalms",
    chapter: 145,
  },
  {
    ref: "Psalm 150:6",
    text: "Let every thing that hath breath praise the LORD. Praise ye the LORD.",
    verse: 6,
    book: "Psalms",
    chapter: 150,
  },
  {
    ref: "Proverbs 3:6",
    text: "In all thy ways acknowledge him, and he shall direct thy paths.",
    verse: 6,
    book: "Proverbs",
    chapter: 3,
  },
  {
    ref: "Proverbs 4:23",
    text: "Keep thy heart with all diligence; for out of it are the issues of life.",
    verse: 23,
    book: "Proverbs",
    chapter: 4,
  },
  {
    ref: "Proverbs 9:10",
    text: "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.",
    verse: 10,
    book: "Proverbs",
    chapter: 9,
  },
  {
    ref: "Proverbs 16:3",
    text: "Commit thy works unto the LORD, and thy thoughts shall be established.",
    verse: 3,
    book: "Proverbs",
    chapter: 16,
  },
  {
    ref: "Proverbs 18:10",
    text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.",
    verse: 10,
    book: "Proverbs",
    chapter: 18,
  },
  {
    ref: "Isaiah 26:3",
    text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
    verse: 3,
    book: "Isaiah",
    chapter: 26,
  },
  {
    ref: "Isaiah 41:10",
    text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.",
    verse: 10,
    book: "Isaiah",
    chapter: 41,
  },
  {
    ref: "Isaiah 43:19",
    text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness.",
    verse: 19,
    book: "Isaiah",
    chapter: 43,
  },
  {
    ref: "Isaiah 55:8",
    text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD.",
    verse: 8,
    book: "Isaiah",
    chapter: 55,
  },
  {
    ref: "Jeremiah 17:7",
    text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.",
    verse: 7,
    book: "Jeremiah",
    chapter: 17,
  },
  {
    ref: "Jeremiah 33:3",
    text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.",
    verse: 3,
    book: "Jeremiah",
    chapter: 33,
  },
  {
    ref: "Lamentations 3:22",
    text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not.",
    verse: 22,
    book: "Lamentations",
    chapter: 3,
  },
  {
    ref: "Lamentations 3:23",
    text: "They are new every morning: great is thy faithfulness.",
    verse: 23,
    book: "Lamentations",
    chapter: 3,
  },
  {
    ref: "Nahum 1:7",
    text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.",
    verse: 7,
    book: "Nahum",
    chapter: 1,
  },
  {
    ref: "Zephaniah 3:17",
    text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy.",
    verse: 17,
    book: "Zephaniah",
    chapter: 3,
  },
  {
    ref: "Malachi 3:10",
    text: "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD.",
    verse: 10,
    book: "Malachi",
    chapter: 3,
  },
  {
    ref: "Matthew 5:16",
    text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
    verse: 16,
    book: "Matthew",
    chapter: 5,
  },
  {
    ref: "Matthew 11:28",
    text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
    verse: 28,
    book: "Matthew",
    chapter: 11,
  },
  {
    ref: "Matthew 22:37",
    text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.",
    verse: 37,
    book: "Matthew",
    chapter: 22,
  },
  {
    ref: "John 3:16",
    text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    verse: 16,
    book: "John",
    chapter: 3,
  },
  {
    ref: "John 14:6",
    text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
    verse: 6,
    book: "John",
    chapter: 14,
  },
  {
    ref: "John 15:5",
    text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit.",
    verse: 5,
    book: "John",
    chapter: 15,
  },
  {
    ref: "Romans 8:38",
    text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come.",
    verse: 38,
    book: "Romans",
    chapter: 8,
  },
  {
    ref: "Romans 12:1",
    text: "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God.",
    verse: 1,
    book: "Romans",
    chapter: 12,
  },
  {
    ref: "1 Corinthians 13:13",
    text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    verse: 13,
    book: "1 Corinthians",
    chapter: 13,
  },
  {
    ref: "Galatians 5:22",
    text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.",
    verse: 22,
    book: "Galatians",
    chapter: 5,
  },
  {
    ref: "Ephesians 2:8",
    text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.",
    verse: 8,
    book: "Ephesians",
    chapter: 2,
  },
  {
    ref: "Ephesians 6:10",
    text: "Finally, my brethren, be strong in the Lord, and in the power of his might.",
    verse: 10,
    book: "Ephesians",
    chapter: 6,
  },
  {
    ref: "Philippians 4:6",
    text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
    verse: 6,
    book: "Philippians",
    chapter: 4,
  },
  {
    ref: "Colossians 3:23",
    text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
    verse: 23,
    book: "Colossians",
    chapter: 3,
  },
  {
    ref: "Hebrews 11:1",
    text: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    verse: 1,
    book: "Hebrews",
    chapter: 11,
  },
  {
    ref: "Hebrews 13:8",
    text: "Jesus Christ the same yesterday, and to day, and for ever.",
    verse: 8,
    book: "Hebrews",
    chapter: 13,
  },
  {
    ref: "James 1:2",
    text: "My brethren, count it all joy when ye fall into divers temptations.",
    verse: 2,
    book: "James",
    chapter: 1,
  },
  {
    ref: "James 1:17",
    text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights.",
    verse: 17,
    book: "James",
    chapter: 1,
  },
  {
    ref: "1 Peter 5:7",
    text: "Casting all your care upon him; for he careth for you.",
    verse: 7,
    book: "1 Peter",
    chapter: 5,
  },
  {
    ref: "1 John 4:19",
    text: "We love him, because he first loved us.",
    verse: 19,
    book: "1 John",
    chapter: 4,
  },
  {
    ref: "Revelation 3:20",
    text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.",
    verse: 20,
    book: "Revelation",
    chapter: 3,
  },
  {
    ref: "Revelation 21:4",
    text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying.",
    verse: 4,
    book: "Revelation",
    chapter: 21,
  },
];
